name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Create virtual environment
        run: python -m venv venv
      - name: Activate virtual environment
        run: source venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Docker image
        run: docker build -t fastapi-app .
      - name: Run Docker container
        run: docker run -d -p 8000:8000 fastapi-app